name: aws-keycloak
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
description: A minimal AWS TypeScript Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
